spring:
  application:
    name: house-rental-management

  datasource:
    url: jdbc:postgresql://localhost:5433/rental_management_db
    username: postgres
    password: rootpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    com.rental: DEBUG
    org.hibernate.SQL: INFO
