
# VNPAY Sandbox Configuration
vnpay.tmnCode=DUMMY_TMN_CODE
vnpay.hashSecret=DUMMY_HASH_SECRET
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/v1/payments/vnpay-return

# VNPAY Configuration
vnpay.tmnCode=THQ1JCH3
vnpay.hashSecret=LLVGLGVAHGJJICUXFSOZVJICUJJKOINJ
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/v1/payments/vnpay-return